export const DEFAULT_LOCALE = "zh-CN";
export const SUPPORTED_LOCALES = ["zh-CN", "en"];
export const LOCALE_STORAGE_KEY = "agent-skill-studio.interface-language";

const zhCN = {
  "app.localOnly": "仅本机",
  "nav.library": "资料库",
  "nav.all": "所有技能",
  "nav.personal": "个人",
  "nav.disabled": "已停用",
  "nav.system": "系统",
  "nav.plugin": "插件",
  "nav.archive": "归档",
  "health.title": "健康状况",
  "health.checking": "正在检查",
  "health.issuesLabel": "存在阻断问题的个人技能",
  "health.issueTitle": "查看 {name} 的阻断问题",
  "health.needsAttention": "{count} 项存在阻断问题",
  "health.normal": "个人技能状态正常",
  "sidebar.skillCategories": "技能分类",
  "sidebar.codexLocation": "Codex 技能位置",
  "sidebar.codexHome": "Codex 主目录",
  "library.title": "技能库",
  "library.loading": "正在读取...",
  "library.export": "导出",
  "library.importBundle": "导入技能迁移包",
  "library.importSkill": "导入技能",
  "library.createSkill": "新建技能",
  "common.settings": "设置",
  "common.language": "界面语言",
  "common.refresh": "刷新",
  "common.close": "关闭",
  "common.cancel": "取消",
  "common.back": "返回",
  "common.done": "完成",
  "common.confirm": "确认",
  "common.checking": "正在检查",
  "common.error": "错误",
  "common.notRun": "未运行",
  "common.files": "文件",
  "common.source": "来源",
  "common.name": "名称",
  "common.rename": "重命名",
  "common.delete": "删除",
  "common.model": "模型",
  "common.requests": "请求",
  "common.location": "位置",
  "common.status": "状态",
  "common.copyFailed": "复制失败：{message}",
  "common.items": "{count} 项",
  "common.fileCount": "{count} 个文件",
  "common.count": "{count} 个",
  "common.required": "必选",
  "common.executable": "可执行",
  "common.emptyContent": "（无内容）",
  "filter.tools": "筛选工具",
  "filter.searchPlaceholder": "搜索名称或描述",
  "filter.sortTitle": "排序方式",
  "filter.sort": "排序",
  "filter.bySource": "来源",
  "filter.byName": "名称",
  "filter.byUpdated": "最近更新",
  "list.skill": "技能",
  "list.trigger": "触发规则",
  "list.results": "{visible} 个结果 · {total} 个已收录",
  "list.viewSkill": "查看 {name}",
  "list.noMatches": "没有匹配的技能",
  "list.adjustFilters": "调整搜索或来源筛选。",
  "source.personal": "个人",
  "source.disabled": "已停用",
  "source.system": "系统",
  "source.plugin": "插件",
  "source.archive": "归档",
  "provenance.githubRepository": "GitHub · {repository}",
  "provenance.local": "本地来源",
  "provenance.unknown": "来源未知",
  "provenance.exactRevision": "已记录精确安装版本",
  "provenance.confirmedRepository": "仓库已确认，原始版本未知",
  "provenance.localRecorded": "已记录本地安装来源",
  "provenance.unknownDetail": "尚无可靠来源证据",
  "provenance.recordFailed": "技能已安装，但未能保存来源记录；当前将显示为来源未知。",
  "provenance.lifecycleRecordFailed": "技能状态已更新，但来源记录未能同步；当前将显示为来源未知。",
  "trigger.sourceManaged": "来源管理",
  "trigger.explicitShort": "明确点名",
  "trigger.contextualShort": "按意图触发",
  "trigger.sourceManagedDetail": "由安装来源管理",
  "trigger.explicitDetail": "仅在明确点名时触发",
  "trigger.contextualDetail": "可根据任务意图触发",
  "detail.label": "技能详情",
  "detail.select": "选择一个技能",
  "detail.inspector": "检查器",
  "detail.close": "关闭详情",
  "detail.state": "状态",
  "detail.trigger": "触发规则",
  "detail.provenance": "来源证据",
  "detail.fileCount": "文件数",
  "detail.updated": "最近修改",
  "detail.copyPath": "复制路径",
  "detail.pathCopied": "路径已复制。",
  "detail.active": "启用",
  "detail.disabled": "停用",
  "detail.archived": "已归档",
  "detail.sourceEnabled": "随来源启用",
  "detail.editPackage": "编辑技能包",
  "detail.viewPackage": "查看技能包",
  "detail.exportSkill": "导出此技能",
  "detail.collections": "分组",
  "update.check": "检查更新",
  "update.reviewKicker": "远端版本审查",
  "update.reviewOnly": "检查未改动本机",
  "update.checkComplete": "检查完成",
  "update.identicalTitle": "无需处理",
  "update.title.remoteChanged": "GitHub 上有新变化",
  "update.title.localChanged": "只有本机内容发生变化",
  "update.title.diverged": "本机和 GitHub 都发生了变化",
  "update.title.localMismatch": "本机内容与安装记录不同",
  "update.title.differentUnknown": "本机与 GitHub 内容不同",
  "update.changedFiles": "变化的文件",
  "update.selectedFile": "文件对比",
  "update.localVersion": "本机",
  "update.showChecks": "查看安全检查",
  "update.hideChecks": "收起安全检查",
  "update.selectChangedFile": "选择一个变化的文件",
  "update.file.added": "GitHub 新增",
  "update.file.removed": "GitHub 已删除",
  "update.file.modified": "已修改",
  "update.file.unchanged": "未变化",
  "update.permissionChanged": "权限变化",
  "update.notOnLocal": "本机没有这个文件。",
  "update.notOnGithub": "GitHub 中已经没有这个文件。",
  "update.attribution.local": "本机修改",
  "update.attribution.remote": "远端更新",
  "update.attribution.unknown": "来源无法判断",
  "update.diffTooLarge": "文件较大，已保留双栏原文对照，不生成逐行差异。",
  "update.unchangedLines": "省略 {count} 行未变化内容",
  "update.sync.add": "添加到本机",
  "update.sync.delete": "从本机删除",
  "update.sync.replace": "使用 GitHub 版本",
  "update.syncTitle.add": "添加这个文件？",
  "update.syncTitle.delete": "删除本机文件？",
  "update.syncTitle.replace": "使用 GitHub 版本替换？",
  "update.syncMessage.add": "将 GitHub 中的 {path} 添加到本机技能。提交前会重新检查远端候选和本机目录。",
  "update.syncMessage.delete": "GitHub 中已经没有 {path}。确认后将从本机技能删除该文件。",
  "update.syncMessage.replace.remote": "安装记录表明本机文件没有修改。确认后将使用 GitHub 版本替换 {path}。提交前会重新检查远端候选和本机目录。",
  "update.syncMessage.replace.local": "{path} 包含本机修改。使用 GitHub 版本会丢弃这个文件的全部本机内容，且不会自动合并。",
  "update.syncMessage.replace.unknown": "无法可靠判断 {path} 的差异来自本机还是 GitHub。继续会使用 GitHub 版本替换整个本机文件，且不会自动合并。",
  "update.syncConfirm.add": "确认添加",
  "update.syncConfirm.delete": "确认删除",
  "update.syncConfirm.replace": "替换本机文件",
  "update.synced.add": "已将 {path} 添加到本机。",
  "update.synced.delete": "已从本机删除 {path}。",
  "update.synced.replace": "已使用 GitHub 版本替换 {path}。",
  "update.unknownRevision": "未知",
  "update.status.identical": "本机内容与远端提交 {remote} 完全一致。",
  "update.status.remoteChanged": "远端提交 {remote} 与已安装版本不同；请先审查变化。",
  "update.status.localChanged": "远端仍是已安装提交 {installed}，但本机内容已有修改。",
  "update.status.diverged": "远端提交和本机内容都已变化；更新前需要人工合并判断。",
  "update.status.localMismatch": "来源提交未变化，但本机内容与安装记录不一致。",
  "update.status.differentUnknown": "远端内容与本机不同；旧来源记录没有原始提交，无法判断哪一方更新。",
  "detail.disable": "停用",
  "detail.enable": "重新启用",
  "detail.archive": "归档",
  "detail.restore": "恢复",
  "detail.delete": "永久删除",
  "detail.readOnly": "只读管理",
  "collections.title": "分组",
  "collections.kicker": "整理技能",
  "collections.create": "新建分组",
  "collections.rename": "重命名分组",
  "collections.manage": "管理分组",
  "collections.membership": "所属分组",
  "collections.empty": "尚未创建分组",
  "collections.noMembership": "尚无分组，可先新建一个。",
  "collections.deleteTitle": "删除分组",
  "collections.deleteMessage": "删除“{name}”只会移除整理信息，不会删除或移动其中的技能。",
  "collections.deleted": "分组已删除。",
  "collections.saved": "所属分组已更新。",
  "collections.lifecycleSyncFailed": "技能状态已更新，但所属分组同步失败；请重新设置归属。",
  "collections.count": "{count} 个技能",
  "package.kicker": "完整技能包",
  "package.unchanged": "未修改",
  "package.unsaved": "有未保存变更",
  "package.export": "导出此技能",
  "package.exportDialogTitle": "导出 {name}",
  "package.exported": "{name} 已导出到 {destination}",
  "package.review": "检查与审查",
  "package.reviewLabel": "技能包审查结果",
  "package.auditPrompt": "修改后运行检查，保存前会核对当前技能包。",
  "package.save": "保存技能包",
  "package.saving": "正在保存",
  "package.files": "文件",
  "package.newFile": "新建文本文件",
  "package.importFile": "添加本机文件",
  "package.newFolder": "新建文件夹",
  "package.selectFile": "选择一个文件",
  "package.selectHint": "从左侧选择文件进行预览或编辑",
  "package.binary": "此文件可随技能包导入导出，但不能在本应用中编辑。",
  "package.validation": "技能包校验",
  "package.changes": "待保存变更",
  "package.noChanges": "尚无变更",
  "package.noValidation": "未发现技能包结构问题",
  "package.filePrompt": "输入文件路径，例如 references/guide.md",
  "package.folderPrompt": "输入文件夹路径，例如 assets/images",
  "package.importPrompt": "输入文件在技能包内的路径",
  "package.renamePrompt": "输入新的相对路径",
  "package.deleteTitle": "从技能包删除",
  "package.deleteMessage": "将删除 {path}。保存技能包前仍可关闭窗口放弃全部变更。",
  "package.saved": "完整技能包已保存。",
  "package.readOnly": "此来源为只读，可预览和整体导出，但不能修改文件。",
  "package.summary": "{files} 个文件 · {size}",
  "package.change.added": "新增",
  "package.change.modified": "修改",
  "package.change.deleted": "删除",
  "package.change.moved": "移动",
  "package.validation.scripts-present": "包含脚本；本应用不会执行这些文件。",
  "package.validation.executable-file": "此文件具有可执行权限；本应用不会运行它。",
  "package.validation.missing-skill-document": "技能包根目录必须包含 SKILL.md。",
  "package.validation.skill-document-too-large": "SKILL.md 超出可编辑文本大小限制。",
  "package.validation.skill-document-not-text": "SKILL.md 必须是 UTF-8 文本。",
  "package.validation.skill-identity-change": "SKILL.md 名称不能改变当前技能包的身份。",
  "editor.close": "关闭编辑器",
  "editor.kicker": "技能草稿",
  "editor.newTitle": "新建技能",
  "editor.unchanged": "未修改",
  "editor.unsaved": "有未保存修改",
  "editor.notCreated": "尚未创建",
  "editor.deepAudit": "深度审查",
  "editor.recheck": "重新检查",
  "editor.create": "创建技能",
  "editor.label": "技能编辑器",
  "editor.modeLabel": "编辑方式",
  "editor.guided": "引导编辑",
  "editor.source": "源码",
  "editor.skillName": "技能名称",
  "editor.purpose": "用途与触发条件",
  "editor.structure": "文档结构",
  "editor.body": "正文",
  "editor.sourceLabel": "SKILL.md 源码",
  "editor.reviewLabel": "草稿检查结果",
  "editor.sectionTitle": "{title} 标题",
  "editor.sectionContent": "{title} 内容",
  "editor.sectionTitleRequired": "章节标题不能为空。",
  "editor.collapseSection": "收起章节",
  "editor.expandSection": "展开章节",
  "editor.collapseNamed": "收起 {title}",
  "editor.expandNamed": "展开 {title}",
  "audit.conclusion": "检查结论",
  "audit.waiting": "等待检查",
  "audit.inProgress": "检查中",
  "audit.currentDraft": "正在检查当前草稿。",
  "audit.creationPreview": "创建预览",
  "audit.creationLocation": "创建位置",
  "audit.waitingName": "等待有效名称",
  "audit.cloud": "云端深度审查",
  "audit.waitingCloud": "等待审查",
  "audit.findings": "发现与证据",
  "audit.diff": "版本差异",
  "audit.notModified": "尚未修改",
  "audit.before": "修改前",
  "audit.draft": "草稿",
  "audit.loadingTitle": "正在检查",
  "audit.loadingSummary": "正在分析结构、触发范围和高影响操作。",
  "audit.failed": "检查未完成",
  "audit.severity.blocker": "阻断",
  "audit.severity.warning": "警告",
  "audit.severity.info": "信息",
  "audit.confidence.high": "高置信",
  "audit.confidence.medium": "中置信",
  "audit.confidence.low": "低置信",
  "audit.dismissed": "复核后排除",
  "audit.viewEvidence": "查看证据",
  "audit.falsePositiveReview": "误报复核：{note}",
  "audit.deep.clearTitle": "未发现经复核的语义风险",
  "audit.deep.clearBadge": "未命中",
  "audit.deep.clearSummary": "这次云端审查没有保留风险项；不代表技能安全。",
  "audit.deep.reviewTitle": "发现需要人工复核的行为",
  "audit.deep.reviewBadge": "需复核",
  "audit.deep.reviewSummary": "请根据文件证据判断这些能力是否符合预期。",
  "audit.deep.blockTitle": "发现高影响语义风险",
  "audit.deep.blockBadge": "高风险",
  "audit.deep.blockSummary": "模型审查保留了高影响风险项，请先修改或人工确认来源。",
  "audit.deep.meta": "{mode} · {model} · {files} 个文件 · {requests} 次请求{dismissed}",
  "audit.deep.dismissedSuffix": " · 排除 {count} 项",
  "audit.baseline.clearTitle": "基础检查未发现已知阻断模式",
  "audit.baseline.clearBadge": "可继续",
  "audit.baseline.clearSummary": "仅表示内置规则没有命中；不代表技能已通过完整安全审计。",
  "audit.baseline.reviewTitle": "需要人工复核",
  "audit.baseline.reviewBadge": "需复核",
  "audit.baseline.reviewSummary": "保存前请阅读下方证据，并确认这些行为符合预期。",
  "audit.baseline.blockTitle": "建议阻止",
  "audit.baseline.blockBadge": "已阻止",
  "audit.baseline.blockSummary": "草稿包含结构错误或高影响操作，解决后才能保存。",
  "finding.missing-frontmatter.title": "缺少技能基本信息",
  "finding.missing-frontmatter.explanation": "文件开头需要包含名称和用途，智能体才能识别这个技能。",
  "finding.missing-name.title": "缺少技能名称",
  "finding.missing-name.explanation": "名称用于识别技能，不能为空。",
  "finding.invalid-name.title": "技能名称格式不兼容",
  "finding.invalid-name.explanation": "名称只能包含小写字母、数字和单个连字符。",
  "finding.identity-change.title": "名称与当前技能不一致",
  "finding.identity-change.explanation": "直接修改名称会让文件夹身份与技能身份分离，请通过复制创建新技能。",
  "finding.missing-description.title": "缺少使用说明",
  "finding.missing-description.explanation": "智能体需要用途和触发条件来判断何时使用这个技能。",
  "finding.contextual-trigger.title": "采用按意图触发",
  "finding.contextual-trigger.explanation": "智能体可以在任务意图与用途匹配时加载这个技能；这与明确点名触发是两种合法策略。",
  "finding.thin-instructions.title": "工作步骤过少",
  "finding.thin-instructions.explanation": "说明太短时，智能体可能无法稳定完成任务或处理边界情况。",
  "finding.baseline-clear.title": "基础检查未发现阻断项",
  "finding.baseline-clear.explanation": "这表示当前规则没有命中问题，不代表技能绝对安全。",
  "finding.remote-code-execution.title": "下载内容后直接执行",
  "finding.remote-code-execution.explanation": "远程内容未经检查就交给命令解释器执行，可能直接控制本机。",
  "finding.destructive-filesystem.title": "发现破坏性文件操作",
  "finding.destructive-filesystem.explanation": "该指令可能递归删除数据、抹除磁盘或直接写入设备。",
  "finding.destructive-data-intent.title": "要求大范围删除用户数据",
  "finding.destructive-data-intent.explanation": "即使没有给出具体命令，这条指令也要求删除或抹除大量用户、项目或系统数据。",
  "finding.credential-exfiltration.title": "敏感数据可能被传出本机",
  "finding.credential-exfiltration.explanation": "同一条指令同时读取凭据位置并执行外部传输。",
  "finding.command-execution.title": "包含命令或解释器执行",
  "finding.command-execution.explanation": "技能可能启动高权限命令、命令行解释器或语言运行时，请核对参数和作用范围。",
  "finding.persistence-change.title": "可能修改持久化启动配置",
  "finding.persistence-change.explanation": "技能可能在登录、启动或定时任务中持续运行。",
  "finding.dependency-installation.title": "包含依赖或软件安装",
  "finding.dependency-installation.explanation": "安装会引入新的可执行代码和供应链依赖，请确认来源与固定版本。",
  "finding.network-access.title": "包含网络访问",
  "finding.network-access.explanation": "技能可能与外部地址交换数据，请确认目的地和发送内容。",
  "finding.sensitive-data-access.title": "可能接触凭据或敏感配置",
  "finding.sensitive-data-access.explanation": "技能提及密钥、令牌或常见凭据位置，请确认读取和输出范围。",
  "finding.prompt-override.title": "包含覆盖或隐藏指令",
  "finding.prompt-override.explanation": "这类语句可能改变智能体的既有约束或隐藏行为，需要人工理解上下文。",
  "finding.encoded-payload.title": "包含编码或混淆载荷",
  "finding.encoded-payload.explanation": "编码内容可能隐藏实际命令或数据，需要先解码并检查再决定是否使用。",
  "finding.staged-download-execution.title": "下载与执行可能分阶段发生",
  "finding.staged-download-execution.explanation": "文档同时包含网络获取和命令执行，但不在同一行；请追踪下载文件如何被使用。",
  "finding.non-text-skill-document.title": "SKILL.md 不是可读取的文本",
  "finding.non-text-skill-document.explanation": "Codex 技能的根说明文件必须是 UTF-8 文本。",
  "compat.bundle-integrity.label": "技能迁移包完整性",
  "compat.bundle-integrity.detail": "文件路径、大小、SHA-256 与迁移包校验值已全部验证。",
  "compat.skill-document.label": "SKILL.md",
  "compat.skill-document.pass": "根说明文件是 UTF-8 文本并包含文档头信息。",
  "compat.skill-document.fail": "根说明文件必须是 UTF-8 文本并包含文档头信息。",
  "compat.directory-identity.label": "目录与文档身份",
  "compat.directory-identity.pass": "目录名与技能名称一致。",
  "compat.directory-identity.fail": "技能迁移包目录名必须与 SKILL.md 名称一致。",
  "compat.description.label": "用途与触发条件",
  "compat.description.pass": "用途和触发条件已提供。",
  "compat.description.fail": "缺少用途说明，Codex 无法判断何时使用。",
  "compat.description.review": "采用按意图触发，这是受支持的策略。",
  "compat.skill-name.label": "技能名称",
  "compat.skill-name.pass": "名称符合 Codex 命名规则。",
  "compat.skill-name.fail": "名称只能使用小写字母、数字和单个连字符。",
  "compat.executable-files.label": "可执行支持文件",
  "compat.executable-files.pass": "没有声明可执行支持文件。",
  "compat.executable-files.review": "发现可执行支持文件；暂存期间不会运行，请在安装前确认用途。",
  "compat.staged-integrity.label": "暂存文件清单",
  "compat.staged-integrity.detail": "已记录全部文件的大小、权限和 SHA-256；安装前会重新核对。",
  "compat.skill-document-text.label": "SKILL.md 文本格式",
  "compat.skill-document-text.pass": "根说明文件可以作为 UTF-8 文本读取。",
  "compat.skill-document-text.fail": "必须使用 UTF-8 文本，当前文件不能被 Codex 读取。",
  "compat.frontmatter.label": "基本信息",
  "compat.frontmatter.pass": "已找到包含名称和用途的文档头信息。",
  "compat.frontmatter.fail": "根文件开头需要以 --- 包围基本信息。",
  "audit.createReady": "可创建",
  "audit.resolveBeforeCreate": "请解决阻断项后再创建",
  "audit.creationConflict": "与{source}来源中的同名技能冲突",
  "candidate.intakeKicker": "导入技能",
  "candidate.chooseSource": "选择来源",
  "candidate.sourceLabel": "技能来源",
  "candidate.localFolder": "本地文件夹",
  "candidate.githubUrl": "公开 GitHub 地址",
  "candidate.folder": "技能文件夹",
  "candidate.noFolder": "尚未选择文件夹",
  "candidate.chooseFolder": "选择文件夹",
  "candidate.chooseFolderTitle": "选择包含 SKILL.md 的文件夹",
  "candidate.intakeNote": "内容只会暂存到应用缓存并进行本地检查，不会安装或运行其中的文件。",
  "candidate.stageReview": "暂存并审查",
  "candidate.staging": "正在暂存",
  "candidate.selectAll": "全选",
  "candidate.clearAll": "清除选择",
  "candidate.reviewSelection": "审查已选 {count} 项",
  "candidate.reviewQueueItem": "继续审查",
  "candidate.newImport": "新的导入",
  "candidate.repositoryRevision": "{ref} · 固定提交 {sha}",
  "candidate.repositoryListingNote": "发现 {count} 个约定技能。此列表只读取仓库目录信息，尚未下载或审查内容。",
  "candidate.repositoryFilteredNote": "仅显示 {available} 个未安装技能；已根据可靠来源记录隐藏 {installed} 个已安装技能。尚未下载或审查内容。",
  "candidate.repositoryAllInstalled": "发现的 {count} 个技能均已有可靠安装记录，没有需要导入的技能。",
  "candidate.noUninstalledSkills": "没有未安装技能",
  "candidate.repositoryRootSkill": "仓库根技能",
  "candidate.repositoryRootLabel": "仓库根目录",
  "candidate.queueTitle": "待审查队列（{count} 项）",
  "candidate.queueNote": "{repository} · 当前第 {current} / {count} 项。打开后才会暂存该项内容。",
  "candidate.queuePosition": "队列 {current} / {count}",
  "candidate.previousQueueSkill": "上一个队列技能",
  "candidate.nextQueueSkill": "下一个队列技能",
  "candidate.queueComplete": "所选技能已全部完成审查队列。",
  "candidate.repositoryReviewKicker": "仓库技能审查",
  "candidate.selectRepositorySkill": "请至少选择一个仓库中的技能。",
  "candidate.noRepositorySkills": "该仓库根目录没有可导入的约定技能。",
  "candidate.reviewKicker": "导入前审查",
  "candidate.pending": "待导入技能",
  "candidate.temporary": "临时暂存",
  "candidate.notInstalled": "尚未安装",
  "candidate.install": "安装技能",
  "candidate.installing": "正在安装",
  "candidate.sourceVersion": "来源与版本",
  "candidate.compatibility": "Codex 兼容性",
  "candidate.stagedFiles": "暂存文件",
  "candidate.filePreview": "文件预览",
  "candidate.previewPrompt": "选择一个文件以查看暂存内容。",
  "candidate.fileSourceLabel": "候选文件与来源",
  "candidate.reviewLabel": "候选审查结果",
  "candidate.baselineConclusion": "基础检查结论",
  "candidate.readingSkill": "正在读取暂存的 SKILL.md。",
  "candidate.skipped": "未纳入的条目",
  "candidate.enterGithub": "请输入公开 GitHub 地址。",
  "candidate.selectFolder": "请选择包含 SKILL.md 的文件夹。",
  "candidate.previewLoading": "正在读取暂存内容。",
  "candidate.previewBinary": "该文件不是 UTF-8 文本，无法在此预览。文件哈希仍已列入上方清单。",
  "candidate.compatible": "基础兼容",
  "candidate.needsReview": "需复核",
  "candidate.incompatible": "不兼容",
  "candidate.installBlockedTitle": "先解决不兼容结构或阻断问题",
  "candidate.installReadyTitle": "复核安装位置并确认安装",
  "candidate.installed": "技能已安装。请在新任务中使用最新版本。",
  "candidate.installedReindexed": "技能已安装；目录索引已重新读取。请在新任务中使用最新版本。",
  "candidate.skippedIdentical": "已存在完全相同的技能版本，未重复安装。",
  "candidate.installConflict": "目标位置已有同名技能：{path}",
  "candidate.cannotInstall": "该候选当前不能安装，请复核阻断项。",
  "candidate.changed": "候选内容已变化，请关闭后重新暂存并审查。",
  "candidate.source": "来源",
  "candidate.githubPublic": "GitHub 公开仓库",
  "candidate.repository": "仓库",
  "candidate.requestedRef": "请求分支",
  "candidate.resolvedCommit": "固定提交",
  "candidate.skillPath": "技能路径",
  "candidate.repositoryRoot": "仓库根目录",
  "candidate.hash": "候选哈希",
  "candidate.localSource": "本地文件夹",
  "candidate.selectedPath": "选择位置",
  "candidate.allIncluded": "所有暂存文件都在左侧清单中。不支持的条目会直接中止审查，不会被静默忽略。",
  "candidate.excludedIntro": "以下条目未被纳入候选内容：",
  "candidate.defaultName": "候选技能",
  "candidate.versionCommit": "提交 {value}",
  "candidate.versionHash": "候选 {value}",
  "candidate.checkingInstall": "正在检查",
  "candidate.auditReview": "基础检查有需人工复核项",
  "candidate.auditClear": "基础检查无已知阻断项",
  "candidate.deepState": "云端深度审查：{state}",
  "candidate.deepClear": "未保留语义风险项",
  "candidate.deepReview": "有需人工复核项",
  "candidate.deepBlock": "有高影响风险项",
  "candidate.deepNotRun": "云端深度审查：未运行（不影响基础安装门槛）",
  "candidate.installTitle": "安装 {name}",
  "candidate.installSource": "来源版本：{value}",
  "candidate.installDestination": "安装位置：{value}",
  "candidate.installFiles": "文件：{count} 个（安装前将再次核对完整清单与哈希）",
  "candidate.installAudit": "审查状态：{value}",
  "candidate.installGuarantee": "安装不会执行候选中的脚本，也不会覆盖同名技能。",
  "candidate.confirmInstall": "确认安装",
  "bundle.exportTitle": "导出个人技能",
  "bundle.selectAll": "选择全部",
  "bundle.contentSize": "内容大小",
  "bundle.unencrypted": "技能迁移包不加密。确定性检查不能证明其中不存在其他秘密。",
  "bundle.destination": "保存位置",
  "bundle.archiveSize": "归档大小",
  "bundle.serverHeading": "传到 Linux 服务器后",
  "bundle.serverHelp": "在服务器的 Codex 中粘贴这段指令。",
  "bundle.copyServerPrompt": "复制服务器安装指令",
  "bundle.serverPromptCopied": "服务器安装指令已复制。",
  "bundle.previewExport": "检查导出内容",
  "bundle.exporting": "正在导出",
  "bundle.chooseExport": "选择位置并导出",
  "bundle.noExportable": "当前没有可导出的启用个人技能。",
  "bundle.exportDialogTitle": "导出技能迁移包",
  "bundle.fileType": "技能迁移包",
  "bundle.formatLabel": "技能迁移包",
  "bundle.skillsLabel": "技能",
  "bundle.importKicker": "导入技能迁移包",
  "bundle.importVerified": "已验证，尚未安装",
  "bundle.staged": "暂存",
  "bundle.notInstalled": "未安装",
  "bundle.skillsInside": "包内技能",
  "bundle.previewPrompt": "选择一个文件以查看已验证暂存内容。",
  "bundle.stagedStatus": "内容已验证并暂存到应用缓存。",
  "bundle.stagedNotInstalled": "内容已验证并暂存到应用缓存，尚未安装。",
  "bundle.discard": "放弃暂存",
  "bundle.reviewInstall": "复核安装",
  "bundle.installResult": "安装结果",
  "bundle.receipt": "回执",
  "bundle.processed": "已处理",
  "bundle.chooseImport": "选择技能迁移包",
  "bundle.previewLoading": "正在读取已验证暂存内容。",
  "bundle.previewBinary": "该文件不是 UTF-8 文本，完整哈希仍已验证。",
  "bundle.compareLoading": "正在重新核对双方校验值与文件内容。",
  "bundle.compareTitle": "版本比较 · {path}",
  "bundle.importedVersion": "导入版本",
  "bundle.currentVersion": "当前版本",
  "bundle.selectionCount": "{count} 项",
  "bundle.skillFileCount": "{count} 个文件",
  "bundle.importCompatible": "符合基础要求",
  "bundle.importReview": "需要复核",
  "bundle.importIncompatible": "不兼容",
  "bundle.exportBlock.credential-path": "路径看起来用于保存凭据，已阻止导出。",
  "bundle.exportBlock.private-key-material": "文件中发现私钥内容，已阻止导出。",
  "bundle.exportBlock.known-token-format": "文件中发现符合已知令牌格式的内容，已阻止导出。",
  "bundle.exportBlock.credential-assignment": "文件中发现高置信度凭据赋值，已阻止导出。",
  "bundle.exportBlock.resource-limit": "技能超过技能迁移包 v1 的文件、大小或目录深度限制。",
  "bundle.exportBlock.bundle-size-limit": "所选内容超过技能迁移包 v1 的归档大小限制。",
  "bundle.exportBlock.unsafe-entry": "技能包含链接、特殊文件或不受支持的路径。",
  "bundle.exportBlock.source-changed": "检查期间技能发生变化，请重新检查。",
  "bundle.exportBlock.source-not-exportable": "技能迁移包 v1 只导出启用的个人技能。",
  "bundle.exportBlock.duplicate-selection": "同一个技能被重复选择。",
  "bundle.exportBlock.skill-not-found": "技能已不在当前目录中，请刷新后重试。",
  "bundle.exportBlock.default": "该技能当前不能导出。",
  "bundle.status.installed": "已安装",
  "bundle.status.replaced": "已替换",
  "bundle.status.skippedIdentical": "已跳过相同版本",
  "bundle.status.failed": "失败",
  "bundle.classification.new": "新技能",
  "bundle.classification.identical": "完全相同 · 自动跳过",
  "bundle.classification.userConflict": "个人版本冲突",
  "bundle.classification.managedConflict": "受管版本冲突",
  "bundle.classification.incompatible": "不兼容",
  "bundle.delta.unchanged": "相同",
  "bundle.delta.modified": "已修改",
  "bundle.delta.importedOnly": "仅导入版本",
  "bundle.delta.currentOnly": "仅当前版本",
  "bundle.sameNameHeading": "同名版本 · {count}",
  "bundle.sameRevision": "完整校验值相同",
  "bundle.different": "存在差异",
  "bundle.revision": "技能版本校验值 {revision}",
  "bundle.revisionUnavailable": "该目录无法计算可迁移版本校验值",
  "bundle.replacePersonal": "使用导入版本替换当前个人技能",
  "bundle.installVersion": "安装这个导入版本",
  "bundle.selectionReview": "复核安装 {count} 项",
  "bundle.selectionReviewEmpty": "复核安装",
  "bundle.sourceFile": "来源文件",
  "bundle.sourceFileRevision": "来源文件校验值",
  "bundle.bundleRevision": "迁移包校验值",
  "bundle.fileCountWithBytes": "{count} 个 · {bytes}",
  "bundle.auditPrefix": "审查：{label}",
  "bundle.compatibilityHeading": "Codex 兼容性",
  "bundle.verifiedFiles": "已验证文件",
  "bundle.unknownDecision": "未能判断这个技能与当前目录的关系。",
  "bundle.decision.identical": "至少有一个同名技能的完整版本相同，将自动跳过。",
  "bundle.decision.managedConflict": "存在内容不同的系统或插件技能，不能安装或覆盖。",
  "bundle.decision.userConflict": "存在内容不同的个人版本，需要比较并明确确认。",
  "bundle.decision.userBlocked": "存在个人版本冲突，且基础审查含阻断项，不能进入安装确认。",
  "bundle.decision.newBlocked": "当前目录中没有同名技能，但基础审查含阻断项。",
  "bundle.decision.new": "当前目录中没有同名技能，可以进入安装确认。",
  "bundle.decision.incompatible": "这个技能不满足当前 Codex 兼容性或审查要求。",
  "bundle.offer.replace": "将替换当前启用的个人技能；停用和归档版本保持不变。",
  "bundle.offer.createDormant": "将创建一个启用的个人技能；停用和归档版本保持不变。",
  "bundle.offer.create": "只会安装到空闲目标位置；如果目标已存在，将停止且不会覆盖。",
  "bundle.installPreviewMissing": "正在读取已验证暂存内容。",
  "bundle.installPreviewNonText": "该文件不是 UTF-8 文本，完整哈希仍已验证。",
  "bundle.installPreviewTruncated": "仅显示前 {bytes}；完整文件哈希仍已验证。",
  "bundle.fileComparisonMissing": "该版本中没有此文件。",
  "bundle.fileComparisonNonText": "该文件不是 UTF-8 文本。",
  "bundle.fileComparisonTruncated": "仅显示前 {bytes}。",
  "bundle.installCurrent": "替换当前启用的个人技能",
  "bundle.installEnabled": "安装为启用的个人技能",
  "bundle.installConfirmTitle": "安装所选技能版本",
  "bundle.installConfirmMessage": "安装前会重新验证技能迁移包、全部同名版本和目标目录。{recovery}",
  "bundle.recoveryNotice": "被替换的个人技能会先保留恢复副本。",
  "bundle.installStatus": "安装结果：完成 {installed} 项{skipped}{failed}{restart}。",
  "bundle.skippedSuffix": " · 跳过相同 {count} 项",
  "bundle.failedSuffix": " · 失败 {count} 项",
  "bundle.restartSuffix": " · 请重启 Codex 以加载变更",
  "bundle.partialFailure": "部分技能未能安装，请查看逐项回执。",
  "bundle.allProcessed": "所选技能版本已处理完成。",
  "bundle.receiptRefreshFailed": "安装回执已保留；重新检查目录索引失败：{message}",
  "bundle.staleRefreshFailed": "同名版本已变化且重新检查失败。重新导入后才能继续比较或安装。",
  "bundle.receiptRetained": "安装回执已保留，但目录索引重新检查失败。重新导入后才能继续比较或安装。",
  "bundle.previewImportTitle": "版本比较 · {path}",
  "bundle.previewImportVersion": "导入版本",
  "bundle.previewCurrentVersion": "当前版本",
  "bundle.viewRevision": "查看技能版本校验值",
  "bundle.executableAfterInstall": "安装后可执行",
  "bundle.viewSha": "查看 SHA-256",
  "settings.title": "设置",
  "settings.deepAudit": "深度审查",
  "settings.apiMode": "API 模式",
  "settings.baseUrl": "OpenAI 兼容 API 基础地址",
  "settings.apiKey": "API 密钥",
  "settings.modelPlaceholder": "模型名称",
  "settings.remove": "移除配置",
  "settings.test": "测试连接",
  "settings.testing": "测试中",
  "settings.connecting": "正在连接...",
  "settings.connectionSuccess": "连接成功 · {mode} · {endpoint}",
  "settings.connectionFailed": "连接失败：{message}",
  "settings.saveAction": "保存配置",
  "settings.keyStoredPlaceholder": "已存储；留空可继续使用",
  "settings.keyPlaceholder": "输入 API 密钥",
  "settings.keyStored": "API 密钥已保存在此 Mac 的应用私有目录中，应用不会回显、记录或导出。同一 macOS 账户下运行的软件仍可能访问它。",
  "settings.keyWillStore": "保存后，API 密钥将写入仅当前 macOS 账户可读的应用私有目录。同一账户下运行的软件仍可能访问它。",
  "settings.saved": "深度审查配置和 API 密钥已保存在本机。",
  "settings.removeTitle": "移除深度审查配置",
  "settings.removeMessage": "将删除已保存的 API 模式、服务地址、模型名称和本机 API 密钥。",
  "settings.removeConfirm": "确认移除",
  "settings.removed": "深度审查配置已移除。",
  "consent.kicker": "发送前确认",
  "consent.title": "选择离开本机的文件",
  "consent.apiAddress": "API 地址",
  "consent.run": "确认发送并审查",
  "consent.running": "正在审查",
  "consent.requestCount": "{count} 次（威胁判断 + 误报复核）",
  "consent.notUploaded": "{count} 个文件不会上传",
  "consent.notUploadedDefault": "未上传文件",
  "consent.completed": "深度审查完成。",
  "deep.skippedSummary": "{count} 个文件不会上传",
  "deep.fileMetadata": "{size} · SHA-256 {hash}{required}",
  "deep.requiredSuffix": " · 必选",
  "deep.notConfigured": "尚未配置深度审查模型。请先在“设置”中填写 API 模式、基础地址、模型和 API 密钥。",
  "confirm.title": "确认操作",
  "confirm.typeName": "输入技能名称以确认",
  "confirm.submitting": "正在提交",
  "error.operationUnavailable": "此操作将在后续阶段提供。",
  "error.providerNotConfigured": "尚未配置深度审查模型。请先在“设置”中填写 API 模式、基础地址、模型和 API 密钥。",
  "error.generic": "操作没有完成，请重试。",
  "editor.created": "技能已创建。请在新任务中使用最新版本。",
  "editor.createConfirmTitle": "创建新技能",
  "editor.createRiskMessage": "云端深度审查保留了高影响风险项。阅读证据后，仍将在 {destination} 创建 SKILL.md。",
  "editor.createMessage": "将在 {destination} 创建 SKILL.md。",
  "editor.confirmCreate": "确认创建",
  "editor.reviewSaveTitle": "保存需要复核的草稿",
  "editor.reviewSaveDeepMessage": "云端深度审查保留了高影响风险项。阅读证据并确认行为符合预期后再保存。",
  "editor.reviewSaveMessage": "检查发现了需要人工复核的行为。确认这些行为符合预期后再保存。",
  "editor.confirmSave": "确认保存",
  "editor.discardTitle": "放弃未保存修改",
  "editor.discardMessage": "关闭后，这次草稿修改不会保留。",
  "editor.discard": "放弃修改",
  "lifecycle.disableTitle": "停用技能",
  "lifecycle.disableMessage": "停用 {name}？新任务将不再加载它。",
  "lifecycle.disableConfirm": "确认停用",
  "lifecycle.enableTitle": "重新启用技能",
  "lifecycle.enableMessage": "将 {name} 恢复到个人技能？",
  "lifecycle.enableConfirm": "确认启用",
  "lifecycle.archiveTitle": "归档技能",
  "lifecycle.archiveMessage": "将 {name} 移入可恢复归档？",
  "lifecycle.archiveConfirm": "确认归档",
  "lifecycle.restoreTitle": "恢复技能",
  "lifecycle.restoreMessage": "将 {name} 恢复到启用的个人技能？",
  "lifecycle.restoreConfirm": "确认恢复",
  "lifecycle.deleteTitle": "永久删除技能",
  "lifecycle.deleteMessage": "永久删除 {name} 及其全部文件？此操作无法撤销。",
  "lifecycle.deleteConfirm": "永久删除",
  "lifecycle.destinationConflict": "目标位置已有同名目录：{path}",
  "lifecycle.deleted": "{name} 已永久删除。",
  "lifecycle.completed": "{action}完成。请在新任务中使用最新状态。",
  "lifecycle.destination": "目标位置：{path}",
  "lifecycle.actionDisable": "停用",
  "lifecycle.actionEnable": "启用",
  "lifecycle.actionArchive": "归档",
  "lifecycle.actionRestore": "恢复",
  "copy.serverPrompt": "服务器安装指令已复制。",
  "error.code.SKILL_NOT_FOUND": "没有找到这个技能，请刷新后重试。",
  "error.code.READ_ONLY_SOURCE": "只有个人技能可以编辑。",
  "error.code.INVALID_DRAFT": "草稿不能为空，且不能超过 64 KiB。",
  "error.code.STALE_DRAFT": "技能在草稿打开后发生变化，请刷新后再保存。",
  "error.code.STALE_PREVIEW": "草稿在预览后发生变化，请重新检查。",
  "error.code.NAME_CONFLICT": "当前目录中已经存在同名技能。",
  "error.code.INVALID_LIFECYCLE_ACTION": "无法识别这个技能状态操作。",
  "error.code.LIFECYCLE_NOT_ALLOWED": "当前来源不允许执行这个状态操作。",
  "error.code.STALE_DIRECTORY": "技能目录在预览后发生变化，请重新检查操作。",
  "error.code.DELETE_CONFIRMATION_MISMATCH": "请输入归档技能的完整名称以确认永久删除。",
  "error.code.BLOCKING_FINDINGS": "请先解决阻断问题。",
  "error.code.UNSAFE_PATH": "不支持编辑链接或逃逸到目录外的技能文件。",
  "error.code.INVALID_PACKAGE_PATH": "技能包路径无效；只能使用技能内的相对路径。",
  "error.code.PACKAGE_TOO_LARGE": "技能包超出支持的文件数或大小限制。",
  "error.code.PACKAGE_PATH_CONFLICT": "该文件或文件夹路径已经存在。",
  "error.code.INVALID_COLLECTION_NAME": "分组名称需要包含 1 到 60 个可见字符。",
  "error.code.COLLECTION_NOT_FOUND": "该分组已不存在，请刷新后重试。",
  "error.code.DUPLICATE_COLLECTION_NAME": "已经存在同名分组。",
  "error.code.INVALID_COLLECTION_STORE": "分组本地数据无效或超出限制。",
  "error.code.COLLECTION_IO_ERROR": "无法读写本机分组。",
  "error.code.LOCAL_IO_ERROR": "无法访问本机技能目录。",
  "error.code.INVALID_GITHUB_CANDIDATE_URL": "请输入公开的 github.com 仓库或技能目录地址。",
  "error.code.INVALID_LOCAL_CANDIDATE": "所选候选必须是真实文件夹，不能是链接。",
  "error.code.MISSING_SKILL_DOCUMENT": "技能包根目录中必须保留 SKILL.md。",
  "error.code.NO_REPOSITORY_SKILLS": "该仓库没有仓库根技能，也没有位于受支持 skills/ 层级中的技能。",
  "error.code.REPOSITORY_SKILL_LIMIT": "该仓库包含超过 256 个可识别技能，未生成不完整列表。",
  "error.code.UNSAFE_CANDIDATE_ENTRY": "候选包含不安全或不支持的条目。",
  "error.code.CANDIDATE_FILE_LIMIT": "候选文件过多，当前上限为 256 个。",
  "error.code.CANDIDATE_FILE_SIZE_LIMIT": "候选中有文件超过 2 MiB。",
  "error.code.CANDIDATE_TOTAL_SIZE_LIMIT": "候选超过 25 MiB 暂存上限。",
  "error.code.CANDIDATE_DEPTH_LIMIT": "候选目录层级超过支持范围。",
  "error.code.GITHUB_TREE_LIMIT": "GitHub 文件树被截断或超过响应上限。",
  "error.code.INCONSISTENT_GITHUB_SOURCE": "GitHub 来源在下载期间发生变化，请重试。",
  "error.code.GITHUB_RATE_LIMIT": "GitHub 请求已达到速率限制，请稍后重试。",
  "error.code.GITHUB_ACQUISITION_ERROR": "无法从 GitHub 获取候选，请检查网络后重试。",
  "error.code.UNKNOWN_CANDIDATE_SESSION": "候选暂存会话已结束，请重新导入。",
  "error.code.STALE_CANDIDATE": "暂存候选发生变化，请重新开始审查。",
  "error.code.UNKNOWN_CANDIDATE_FILE": "该文件不属于当前暂存候选。",
  "error.code.INVALID_CANDIDATE_FILE_SYNC": "该文件不能执行所选同步操作，请重新检查更新。",
  "error.code.INVALID_PACKAGE_OPERATION": "无法识别这个文件操作，请重新检查更新。",
  "error.code.BINARY_PACKAGE_FILE": "二进制文件不能作为文本直接编辑。",
  "error.code.CANDIDATE_IO_ERROR": "无法在应用缓存中暂存候选。",
  "error.code.GITHUB_UPDATE_PROVENANCE_UNAVAILABLE": "没有足够的 GitHub 来源证据来检查更新。",
  "error.code.GITHUB_UPDATE_READ_ONLY": "只有由用户控制的技能可以检查 GitHub 更新。",
  "error.code.CANDIDATE_INSTALL_BLOCKED": "候选存在阻断问题或兼容性问题，不能安装。",
  "error.code.STALE_INSTALL_PREVIEW": "安装预览已变化，请重新复核目标位置。",
  "error.code.DEEP_AUDIT_NOT_CONFIGURED": "尚未配置深度审查模型。",
  "error.code.INVALID_PROVIDER_ENDPOINT": "请输入有效的 HTTPS API 基础地址；只有本机回环地址可使用 HTTP。",
  "error.code.INVALID_PROVIDER_MODEL": "请输入模型名称。",
  "error.code.STALE_DEEP_AUDIT_PREVIEW": "深度审查预览已过期，请重新确认服务和文件。",
  "error.code.INVALID_DEEP_AUDIT_SELECTION": "所选深度审查文件无效，请重新检查文件清单。",
  "error.code.DEEP_AUDIT_PROVIDER_ERROR": "云端模型请求失败，请检查服务配置和网络。",
  "error.code.INVALID_PROVIDER_RESPONSE": "云端模型没有返回可验证的结构化证据。",
  "error.code.CREDENTIAL_STORE_ERROR": "无法安全地读取或保存本机深度审查凭据。",
  "error.code.PREFERENCES_ERROR": "无法读取或保存深度审查设置。",
  "error.code.BUNDLE_EXPORT_SELECTION_INVALID": "请至少选择一个个人技能。",
  "error.code.BUNDLE_EXPORT_PLAN_STALE": "导出预览已过期，请重新检查所选技能。",
  "error.code.BUNDLE_EXPORT_SOURCE_CHANGED": "技能在导出前发生变化，请重新检查。",
  "error.code.BUNDLE_EXPORT_DESTINATION_INVALID": "请选择现有文件夹中的新 .skillbundle 文件。",
  "error.code.BUNDLE_EXPORT_DESTINATION_EXISTS": "该位置已经有同名文件，请选择新文件名。",
  "error.code.BUNDLE_EXPORT_IO_ERROR": "无法将技能迁移包写入所选位置。",
  "error.code.BUNDLE_IMPORT_SOURCE_INVALID": "请选择普通的 .skillbundle 文件。",
  "error.code.BUNDLE_IMPORT_SOURCE_CHANGED": "读取期间技能迁移包发生变化，请重新选择。",
  "error.code.BUNDLE_IMPORT_SESSION_UNKNOWN": "技能迁移包暂存会话已结束，请重新导入。",
  "error.code.BUNDLE_IMPORT_SESSION_CHANGED": "技能迁移包暂存内容发生变化，请重新导入。",
  "error.code.BUNDLE_LIMIT_EXCEEDED": "技能迁移包超过允许的大小或文件数量限制。",
  "error.code.BUNDLE_IMPORT_IO_ERROR": "无法在应用缓存中暂存技能迁移包。",
  "error.code.BUNDLE_INSTALL_REVIEW_STALE": "安装审查已过期，请按最新同名版本重新选择。",
  "error.code.BUNDLE_INSTALL_MATCH_UNKNOWN": "同名版本发生变化，请重新查看比较结果。",
  "error.code.BUNDLE_INSTALL_FILE_UNKNOWN": "该文件不属于当前版本比较。",
  "error.code.BUNDLE_INSTALL_SELECTION_INVALID": "请至少选择一个当前可安装的版本。",
  "error.code.BUNDLE_INSTALL_BLOCKED": "当前分类、兼容性或审查结果不允许安装。",
  "error.code.BUNDLE_INSTALL_IO_ERROR": "安装遇到本地文件错误，请查看逐项回执。"
};

const en = {
  ...zhCN,
  "app.localOnly": "On this Mac",
  "nav.library": "Library",
  "nav.all": "All Skills",
  "nav.personal": "Personal",
  "nav.disabled": "Disabled",
  "nav.system": "System",
  "nav.plugin": "Plugins",
  "nav.archive": "Archive",
  "health.title": "Health",
  "health.checking": "Checking",
  "health.issuesLabel": "Personal Skills with blocking findings",
  "health.issueTitle": "View blocking findings for {name}",
  "health.needsAttention": "{count} with blocking findings",
  "health.normal": "Personal Skills look normal",
  "sidebar.skillCategories": "Skill categories",
  "sidebar.codexLocation": "Codex Skills location",
  "sidebar.codexHome": "Codex Home",
  "library.title": "Skill Library",
  "library.loading": "Loading...",
  "library.export": "Export",
  "library.importBundle": "Import Bundle",
  "library.importSkill": "Import Skill",
  "library.createSkill": "New Skill",
  "common.settings": "Settings",
  "common.language": "Interface Language",
  "common.refresh": "Refresh",
  "common.close": "Close",
  "common.cancel": "Cancel",
  "common.back": "Back",
  "common.done": "Done",
  "common.confirm": "Confirm",
  "common.checking": "Checking",
  "common.error": "Error",
  "common.notRun": "Not run",
  "common.files": "Files",
  "common.source": "Source",
  "common.name": "Name",
  "common.rename": "Rename",
  "common.delete": "Delete",
  "common.model": "Model",
  "common.requests": "Requests",
  "common.location": "Location",
  "common.status": "Status",
  "common.copyFailed": "Copy failed: {message}",
  "common.items": "{count} items",
  "common.fileCount": "{count} files",
  "common.count": "{count}",
  "common.required": "Required",
  "common.executable": "Executable",
  "common.emptyContent": "(No content)",
  "filter.tools": "Filter tools",
  "filter.searchPlaceholder": "Search names or descriptions",
  "filter.sortTitle": "Sort order",
  "filter.sort": "Sort",
  "filter.bySource": "Source",
  "filter.byName": "Name",
  "filter.byUpdated": "Recently updated",
  "list.skill": "Skill",
  "list.trigger": "Trigger",
  "list.results": "{visible} results · {total} in library",
  "list.viewSkill": "View {name}",
  "list.noMatches": "No matching Skills",
  "list.adjustFilters": "Change the search or source filter.",
  "source.personal": "Personal",
  "source.disabled": "Disabled",
  "source.system": "System",
  "source.plugin": "Plugin",
  "source.archive": "Archive",
  "provenance.githubRepository": "GitHub · {repository}",
  "provenance.local": "Local source",
  "provenance.unknown": "Unknown source",
  "provenance.exactRevision": "Exact installed revision recorded",
  "provenance.confirmedRepository": "Repository confirmed; original revision unknown",
  "provenance.localRecorded": "Local installation source recorded",
  "provenance.unknownDetail": "No reliable provenance evidence yet",
  "provenance.recordFailed": "The Skill was installed, but its provenance could not be recorded. It will appear under Unknown source.",
  "provenance.lifecycleRecordFailed": "The Skill state changed, but its provenance could not be synchronized. It will appear under Unknown source.",
  "trigger.sourceManaged": "Source-managed",
  "trigger.explicitShort": "Explicit name",
  "trigger.contextualShort": "Intent-based",
  "trigger.sourceManagedDetail": "Managed by its installed source",
  "trigger.explicitDetail": "Triggers only when explicitly named",
  "trigger.contextualDetail": "May trigger from task intent",
  "detail.label": "Skill details",
  "detail.select": "Select a Skill",
  "detail.inspector": "Inspector",
  "detail.close": "Close details",
  "detail.state": "State",
  "detail.trigger": "Trigger",
  "detail.provenance": "Provenance",
  "detail.fileCount": "Files",
  "detail.updated": "Last modified",
  "detail.copyPath": "Copy path",
  "detail.pathCopied": "Path copied.",
  "detail.active": "Enabled",
  "detail.disabled": "Disabled",
  "detail.archived": "Archived",
  "detail.sourceEnabled": "Enabled by source",
  "detail.editPackage": "Edit Package",
  "detail.viewPackage": "View Package",
  "detail.exportSkill": "Export This Skill",
  "detail.collections": "Collections",
  "update.check": "Check for Updates",
  "update.reviewKicker": "Remote Version Review",
  "update.reviewOnly": "Local files unchanged",
  "update.checkComplete": "Check Complete",
  "update.identicalTitle": "No Action Needed",
  "update.title.remoteChanged": "GitHub Has New Changes",
  "update.title.localChanged": "Only the Local Copy Changed",
  "update.title.diverged": "Both Local and GitHub Copies Changed",
  "update.title.localMismatch": "Local Content Differs From the Install Record",
  "update.title.differentUnknown": "Local and GitHub Content Differ",
  "update.changedFiles": "Changed Files",
  "update.selectedFile": "File Comparison",
  "update.localVersion": "Local",
  "update.showChecks": "Show Safety Checks",
  "update.hideChecks": "Hide Safety Checks",
  "update.selectChangedFile": "Select a changed file",
  "update.file.added": "Added on GitHub",
  "update.file.removed": "Removed on GitHub",
  "update.file.modified": "Modified",
  "update.file.unchanged": "Unchanged",
  "update.permissionChanged": "Mode changed",
  "update.notOnLocal": "This file is not present locally.",
  "update.notOnGithub": "This file is no longer present on GitHub.",
  "update.attribution.local": "Local edit",
  "update.attribution.remote": "Remote update",
  "update.attribution.unknown": "Attribution unavailable",
  "update.diffTooLarge": "This file is large. The side-by-side source view is retained instead of a line Diff.",
  "update.unchangedLines": "{count} unchanged lines hidden",
  "update.sync.add": "Add to Local",
  "update.sync.delete": "Delete Local File",
  "update.sync.replace": "Use GitHub Version",
  "update.syncTitle.add": "Add This File?",
  "update.syncTitle.delete": "Delete the Local File?",
  "update.syncTitle.replace": "Replace With the GitHub Version?",
  "update.syncMessage.add": "Add {path} from GitHub to the local Skill. The remote candidate and local directory are rechecked before commit.",
  "update.syncMessage.delete": "{path} is no longer on GitHub. Confirm to delete it from the local Skill.",
  "update.syncMessage.replace.remote": "The install record indicates that the local file was not edited. Confirm to replace {path} with the GitHub version. The remote candidate and local directory are rechecked before commit.",
  "update.syncMessage.replace.local": "{path} contains local edits. Using the GitHub version discards all local content in this file and does not merge it.",
  "update.syncMessage.replace.unknown": "The app cannot reliably attribute the differences in {path} to either the local copy or GitHub. Continuing replaces the complete local file with the GitHub version and does not merge it.",
  "update.syncConfirm.add": "Add File",
  "update.syncConfirm.delete": "Delete File",
  "update.syncConfirm.replace": "Replace Local File",
  "update.synced.add": "Added {path} locally.",
  "update.synced.delete": "Deleted local file {path}.",
  "update.synced.replace": "Replaced {path} with the GitHub version.",
  "update.unknownRevision": "unknown",
  "update.status.identical": "Local content exactly matches remote commit {remote}.",
  "update.status.remoteChanged": "Remote commit {remote} differs from the installed version. Review the changes first.",
  "update.status.localChanged": "The remote is still installed commit {installed}, but local content has changed.",
  "update.status.diverged": "Both the remote commit and local content changed. Review and reconcile them manually.",
  "update.status.localMismatch": "The source commit is unchanged, but local content differs from the install record.",
  "update.status.differentUnknown": "Remote and local content differ. This legacy source has no installed commit, so neither side can be called newer.",
  "detail.disable": "Disable",
  "detail.enable": "Enable",
  "detail.archive": "Archive",
  "detail.restore": "Restore",
  "detail.delete": "Delete Permanently",
  "detail.readOnly": "Read-only",
  "collections.title": "Collections",
  "collections.kicker": "Organize Skills",
  "collections.create": "New Collection",
  "collections.rename": "Rename Collection",
  "collections.manage": "Manage Collections",
  "collections.membership": "Collection Membership",
  "collections.empty": "No Collections yet",
  "collections.noMembership": "Create a Collection first.",
  "collections.deleteTitle": "Delete Collection",
  "collections.deleteMessage": "Deleting “{name}” removes only organization metadata. It does not delete or move any Skill.",
  "collections.deleted": "Collection deleted.",
  "collections.saved": "Collection membership updated.",
  "collections.lifecycleSyncFailed": "The Skill state changed, but Collection membership could not be synchronized. Set its membership again.",
  "collections.count": "{count} Skills",
  "package.kicker": "Complete Skill Package",
  "package.unchanged": "No changes",
  "package.unsaved": "Unsaved changes",
  "package.export": "Export This Skill",
  "package.exportDialogTitle": "Export {name}",
  "package.exported": "{name} was exported to {destination}",
  "package.review": "Review Package",
  "package.reviewLabel": "Package review results",
  "package.auditPrompt": "Run a review after editing. The Package is rechecked before saving.",
  "package.save": "Save Package",
  "package.saving": "Saving",
  "package.files": "Files",
  "package.newFile": "New text file",
  "package.importFile": "Add local file",
  "package.newFolder": "New folder",
  "package.selectFile": "Select a file",
  "package.selectHint": "Select a file on the left to preview or edit it",
  "package.binary": "This file is included in Package import and export but cannot be edited in Studio.",
  "package.validation": "Package Validation",
  "package.changes": "Pending Changes",
  "package.noChanges": "No changes yet",
  "package.noValidation": "No Package structure issues found",
  "package.filePrompt": "Enter a path such as references/guide.md",
  "package.folderPrompt": "Enter a folder path such as assets/images",
  "package.importPrompt": "Enter the file path inside the Package",
  "package.renamePrompt": "Enter the new relative path",
  "package.deleteTitle": "Delete from Package",
  "package.deleteMessage": "This will remove {path}. You can still close the window to discard all changes before saving.",
  "package.saved": "Complete Skill Package saved.",
  "package.readOnly": "This source is read-only. You can preview and export the Package but cannot change files.",
  "package.summary": "{files} files · {size}",
  "package.change.added": "Added",
  "package.change.modified": "Modified",
  "package.change.deleted": "Deleted",
  "package.change.moved": "Moved",
  "package.validation.scripts-present": "Contains scripts; Studio never executes these files.",
  "package.validation.executable-file": "This file is executable; Studio never runs it.",
  "package.validation.missing-skill-document": "SKILL.md is required at the Package root.",
  "package.validation.skill-document-too-large": "SKILL.md exceeds the editable text limit.",
  "package.validation.skill-document-not-text": "SKILL.md must be UTF-8 text.",
  "package.validation.skill-identity-change": "The SKILL.md name cannot change this Package identity.",
  "editor.close": "Close editor",
  "editor.kicker": "Skill Draft",
  "editor.newTitle": "New Skill",
  "editor.unchanged": "No changes",
  "editor.unsaved": "Unsaved changes",
  "editor.notCreated": "Not created",
  "editor.deepAudit": "Deep Audit",
  "editor.recheck": "Check Again",
  "editor.create": "Create Skill",
  "editor.label": "Skill editor",
  "editor.modeLabel": "Editing mode",
  "editor.guided": "Guided",
  "editor.source": "Source",
  "editor.skillName": "Skill name",
  "editor.purpose": "Purpose and triggers",
  "editor.structure": "Document structure",
  "editor.body": "Body",
  "editor.sourceLabel": "SKILL.md source",
  "editor.reviewLabel": "Draft review",
  "editor.sectionTitle": "{title} heading",
  "editor.sectionContent": "{title} content",
  "editor.sectionTitleRequired": "Section headings cannot be empty.",
  "editor.collapseSection": "Collapse section",
  "editor.expandSection": "Expand section",
  "editor.collapseNamed": "Collapse {title}",
  "editor.expandNamed": "Expand {title}",
  "audit.conclusion": "Check Result",
  "audit.waiting": "Waiting",
  "audit.inProgress": "Checking",
  "audit.currentDraft": "Checking the current draft.",
  "audit.creationPreview": "Creation preview",
  "audit.creationLocation": "Create at",
  "audit.waitingName": "Waiting for a valid name",
  "audit.cloud": "Cloud Deep Audit",
  "audit.waitingCloud": "Waiting",
  "audit.findings": "Findings and Evidence",
  "audit.diff": "Version Differences",
  "audit.notModified": "No changes yet",
  "audit.before": "Before",
  "audit.draft": "Draft",
  "audit.loadingTitle": "Checking",
  "audit.loadingSummary": "Analyzing structure, trigger scope, and high-impact behavior.",
  "audit.failed": "Check incomplete",
  "audit.severity.blocker": "Blocking",
  "audit.severity.warning": "Warning",
  "audit.severity.info": "Info",
  "audit.confidence.high": "High confidence",
  "audit.confidence.medium": "Medium confidence",
  "audit.confidence.low": "Low confidence",
  "audit.dismissed": "Dismissed after review",
  "audit.viewEvidence": "View evidence",
  "audit.falsePositiveReview": "False-positive review: {note}",
  "audit.deep.clearTitle": "No semantic risks remained after review",
  "audit.deep.clearBadge": "No match",
  "audit.deep.clearSummary": "This cloud review retained no risk findings; it does not mean the Skill is safe.",
  "audit.deep.reviewTitle": "Behavior needs human review",
  "audit.deep.reviewBadge": "Review",
  "audit.deep.reviewSummary": "Use the file evidence to decide whether these capabilities are expected.",
  "audit.deep.blockTitle": "High-impact semantic risk found",
  "audit.deep.blockBadge": "High risk",
  "audit.deep.blockSummary": "The model retained high-impact findings. Edit the Skill or verify its source before continuing.",
  "audit.deep.meta": "{mode} · {model} · {files} files · {requests} requests{dismissed}",
  "audit.deep.dismissedSuffix": " · {count} dismissed",
  "audit.baseline.clearTitle": "No known blocking pattern found",
  "audit.baseline.clearBadge": "Continue",
  "audit.baseline.clearSummary": "This only means the built-in rules did not match; it is not a complete security audit.",
  "audit.baseline.reviewTitle": "Human review required",
  "audit.baseline.reviewBadge": "Review",
  "audit.baseline.reviewSummary": "Read the evidence below and confirm that the behavior is expected before saving.",
  "audit.baseline.blockTitle": "Blocking findings",
  "audit.baseline.blockBadge": "Blocked",
  "audit.baseline.blockSummary": "The draft has structural errors or high-impact behavior that must be resolved before saving.",
  "finding.missing-frontmatter.title": "Missing Skill metadata",
  "finding.missing-frontmatter.explanation": "The file needs a name and purpose at the top so the Agent can identify this Skill.",
  "finding.missing-name.title": "Missing Skill name",
  "finding.missing-name.explanation": "The name identifies the Skill and cannot be empty.",
  "finding.invalid-name.title": "Incompatible Skill name format",
  "finding.invalid-name.explanation": "The name may contain only lowercase letters, numbers, and single hyphens.",
  "finding.identity-change.title": "Name does not match the current Skill",
  "finding.identity-change.explanation": "Changing the name separates the folder identity from the Skill identity. Create a new Skill by copying it instead.",
  "finding.missing-description.title": "Missing usage description",
  "finding.missing-description.explanation": "The Agent needs a purpose and trigger conditions to decide when to use this Skill.",
  "finding.contextual-trigger.title": "Uses intent-based triggering",
  "finding.contextual-trigger.explanation": "The Agent may load this Skill when the task intent matches its purpose. This is a supported strategy alongside explicit naming.",
  "finding.thin-instructions.title": "Too few workflow steps",
  "finding.thin-instructions.explanation": "A short description can make the Agent less consistent around the task and its edge cases.",
  "finding.baseline-clear.title": "No blocking finding in the baseline check",
  "finding.baseline-clear.explanation": "The current rules found no issue. This is not an absolute safety guarantee.",
  "finding.remote-code-execution.title": "Executes downloaded content directly",
  "finding.remote-code-execution.explanation": "Remote content is passed to a command interpreter without review and could control the local machine.",
  "finding.destructive-filesystem.title": "Destructive file operation found",
  "finding.destructive-filesystem.explanation": "This instruction may recursively delete data, erase a disk, or write directly to a device.",
  "finding.destructive-data-intent.title": "Requests broad deletion of user data",
  "finding.destructive-data-intent.explanation": "Even without a concrete command, this instruction asks to delete or erase a large scope of user, project, or system data.",
  "finding.credential-exfiltration.title": "Sensitive data may leave the Mac",
  "finding.credential-exfiltration.explanation": "The same instruction reads a credential location and performs an external transfer.",
  "finding.command-execution.title": "Contains command or interpreter execution",
  "finding.command-execution.explanation": "The Skill may start privileged commands, a shell, or a language runtime. Check the arguments and scope.",
  "finding.persistence-change.title": "May change persistent startup configuration",
  "finding.persistence-change.explanation": "The Skill may continue running at login, startup, or on a schedule.",
  "finding.dependency-installation.title": "Installs dependencies or software",
  "finding.dependency-installation.explanation": "Installation introduces executable code and supply-chain dependencies. Confirm the source and pinned version.",
  "finding.network-access.title": "Contains network access",
  "finding.network-access.explanation": "The Skill may exchange data with an external address. Confirm the destination and payload.",
  "finding.sensitive-data-access.title": "May access credentials or sensitive configuration",
  "finding.sensitive-data-access.explanation": "The Skill mentions keys, tokens, or common credential locations. Confirm the read and output scope.",
  "finding.prompt-override.title": "Contains override or hidden instructions",
  "finding.prompt-override.explanation": "These statements may change the Agent's constraints or conceal behavior and require contextual review.",
  "finding.encoded-payload.title": "Contains encoded or obfuscated payloads",
  "finding.encoded-payload.explanation": "Encoded content may hide commands or data. Decode and inspect it before deciding whether to use it.",
  "finding.staged-download-execution.title": "Download and execution may be staged",
  "finding.staged-download-execution.explanation": "The document contains both network retrieval and command execution in separate instructions. Trace how the downloaded file is used.",
  "finding.non-text-skill-document.title": "SKILL.md is not readable text",
  "finding.non-text-skill-document.explanation": "The root Codex Skill document must be UTF-8 text.",
  "compat.bundle-integrity.label": "Bundle integrity",
  "compat.bundle-integrity.detail": "Paths, sizes, SHA-256 values, and the Bundle revision are verified.",
  "compat.skill-document.label": "SKILL.md",
  "compat.skill-document.pass": "The root document is UTF-8 text and contains frontmatter.",
  "compat.skill-document.fail": "The root document must be UTF-8 text and contain frontmatter.",
  "compat.directory-identity.label": "Directory and document identity",
  "compat.directory-identity.pass": "The directory name matches the Skill name.",
  "compat.directory-identity.fail": "The Bundle directory name must match the SKILL.md name.",
  "compat.description.label": "Purpose and triggers",
  "compat.description.pass": "A purpose and trigger strategy are present.",
  "compat.description.fail": "A purpose is missing, so Codex cannot decide when to use it.",
  "compat.description.review": "Uses intent-based triggering, which is supported.",
  "compat.skill-name.label": "Skill name",
  "compat.skill-name.pass": "The name follows Codex naming rules.",
  "compat.skill-name.fail": "The name may contain only lowercase letters, numbers, and single hyphens.",
  "compat.executable-files.label": "Executable support files",
  "compat.executable-files.pass": "No executable support files are declared.",
  "compat.executable-files.review": "Executable support files were found. They are not run during staging; confirm their purpose before installing.",
  "compat.staged-integrity.label": "Staged file manifest",
  "compat.staged-integrity.detail": "Every file's size, mode, and SHA-256 are recorded and will be rechecked before installation.",
  "compat.skill-document-text.label": "SKILL.md text format",
  "compat.skill-document-text.pass": "The root document can be read as UTF-8 text.",
  "compat.skill-document-text.fail": "The root document must be UTF-8 text and cannot currently be read by Codex.",
  "compat.frontmatter.label": "Metadata",
  "compat.frontmatter.pass": "Frontmatter with a name and purpose was found.",
  "compat.frontmatter.fail": "The root file must begin with metadata enclosed by ---.",
  "audit.createReady": "Ready to create",
  "audit.resolveBeforeCreate": "Resolve blocking findings before creating",
  "audit.creationConflict": "Conflicts with a same-name Skill in {source}",
  "candidate.intakeKicker": "Import Skill",
  "candidate.chooseSource": "Choose a Source",
  "candidate.sourceLabel": "Skill source",
  "candidate.localFolder": "Local Folder",
  "candidate.githubUrl": "Public GitHub URL",
  "candidate.folder": "Skill folder",
  "candidate.noFolder": "No folder selected",
  "candidate.chooseFolder": "Choose Folder",
  "candidate.chooseFolderTitle": "Choose a folder containing SKILL.md",
  "candidate.intakeNote": "Content is staged in the app cache for local checks only. Files are not installed or run.",
  "candidate.stageReview": "Stage and Review",
  "candidate.staging": "Staging",
  "candidate.selectAll": "Select All",
  "candidate.clearAll": "Clear Selection",
  "candidate.reviewSelection": "Review {count} Selected",
  "candidate.reviewQueueItem": "Continue Review",
  "candidate.newImport": "New Import",
  "candidate.repositoryRevision": "{ref} · pinned commit {sha}",
  "candidate.repositoryListingNote": "Found {count} conventional Skills. This list reads repository metadata only; no content has been downloaded or reviewed.",
  "candidate.repositoryFilteredNote": "Showing {available} uninstalled Skills. {installed} installed Skills were hidden using reliable provenance records. No content has been downloaded or reviewed.",
  "candidate.repositoryAllInstalled": "All {count} discovered Skills have reliable installation records. There is nothing to import.",
  "candidate.noUninstalledSkills": "No Uninstalled Skills",
  "candidate.repositoryRootSkill": "Repository Root Skill",
  "candidate.repositoryRootLabel": "Repository root",
  "candidate.queueTitle": "Review Queue ({count})",
  "candidate.queueNote": "{repository} · item {current} of {count}. Content is staged only when you open this item.",
  "candidate.queuePosition": "Queue {current} of {count}",
  "candidate.previousQueueSkill": "Previous Queue Skill",
  "candidate.nextQueueSkill": "Next Queue Skill",
  "candidate.queueComplete": "All selected Skills have left the review queue.",
  "candidate.repositoryReviewKicker": "Repository Skill Review",
  "candidate.selectRepositorySkill": "Select at least one Skill from this repository.",
  "candidate.noRepositorySkills": "This repository root has no conventional Skills to import.",
  "candidate.reviewKicker": "Pre-install Review",
  "candidate.pending": "Skill to Import",
  "candidate.temporary": "Temporary staging",
  "candidate.notInstalled": "Not installed",
  "candidate.install": "Install Skill",
  "candidate.installing": "Installing",
  "candidate.sourceVersion": "Source and Version",
  "candidate.compatibility": "Codex Compatibility",
  "candidate.stagedFiles": "Staged Files",
  "candidate.filePreview": "File Preview",
  "candidate.previewPrompt": "Select a file to preview staged content.",
  "candidate.fileSourceLabel": "Candidate files and source",
  "candidate.reviewLabel": "Candidate review",
  "candidate.baselineConclusion": "Baseline Check Result",
  "candidate.readingSkill": "Reading the staged SKILL.md.",
  "candidate.skipped": "Excluded Entries",
  "candidate.enterGithub": "Enter a public GitHub URL.",
  "candidate.selectFolder": "Choose a folder containing SKILL.md.",
  "candidate.previewLoading": "Reading staged content.",
  "candidate.previewBinary": "This file is not UTF-8 text and cannot be previewed here. Its hash is still listed above.",
  "candidate.compatible": "Baseline compatible",
  "candidate.needsReview": "Review",
  "candidate.incompatible": "Incompatible",
  "candidate.installBlockedTitle": "Resolve compatibility or blocking findings first",
  "candidate.installReadyTitle": "Review the destination and confirm installation",
  "candidate.installed": "Skill installed. Use a new task to load the latest version.",
  "candidate.installedReindexed": "Skill installed and the catalog was refreshed. Use a new task to load the latest version.",
  "candidate.skippedIdentical": "An identical Skill version already exists, so nothing was installed.",
  "candidate.installConflict": "A same-name Skill already exists at {path}",
  "candidate.cannotInstall": "This candidate cannot currently be installed. Review the blocking findings.",
  "candidate.changed": "The candidate changed. Close it, then stage and review it again.",
  "candidate.source": "Source",
  "candidate.githubPublic": "Public GitHub repository",
  "candidate.repository": "Repository",
  "candidate.requestedRef": "Requested ref",
  "candidate.resolvedCommit": "Resolved commit",
  "candidate.skillPath": "Skill path",
  "candidate.repositoryRoot": "Repository root",
  "candidate.hash": "Candidate hash",
  "candidate.localSource": "Local folder",
  "candidate.selectedPath": "Selected path",
  "candidate.allIncluded": "Every staged file is listed on the left. Unsupported entries stop review and are never silently ignored.",
  "candidate.excludedIntro": "These entries were excluded from the candidate:",
  "candidate.defaultName": "Candidate Skill",
  "candidate.versionCommit": "Commit {value}",
  "candidate.versionHash": "Candidate {value}",
  "candidate.checkingInstall": "Checking",
  "candidate.auditReview": "The baseline check needs human review",
  "candidate.auditClear": "The baseline check has no known blocking findings",
  "candidate.deepState": "Cloud Deep Audit: {state}",
  "candidate.deepClear": "No semantic findings retained",
  "candidate.deepReview": "Needs human review",
  "candidate.deepBlock": "Has high-impact findings",
  "candidate.deepNotRun": "Cloud Deep Audit: not run (this does not change the baseline installation gate)",
  "candidate.installTitle": "Install {name}",
  "candidate.installSource": "Source version: {value}",
  "candidate.installDestination": "Install at: {value}",
  "candidate.installFiles": "Files: {count} (the full manifest and hashes will be rechecked before installation)",
  "candidate.installAudit": "Audit state: {value}",
  "candidate.installGuarantee": "Installation will not run candidate scripts or overwrite a same-name Skill.",
  "candidate.confirmInstall": "Confirm Installation",
  "bundle.exportTitle": "Export Personal Skills",
  "bundle.selectAll": "Select All",
  "bundle.contentSize": "Content size",
  "bundle.unencrypted": "Bundles are not encrypted. Deterministic checks cannot prove that no other secrets are present.",
  "bundle.destination": "Saved to",
  "bundle.archiveSize": "Archive size",
  "bundle.serverHeading": "After Transfer to Linux",
  "bundle.serverHelp": "Paste this instruction into Codex on the server.",
  "bundle.copyServerPrompt": "Copy Server Installation Instruction",
  "bundle.serverPromptCopied": "Server installation instruction copied.",
  "bundle.previewExport": "Review Export",
  "bundle.exporting": "Exporting",
  "bundle.chooseExport": "Choose Location and Export",
  "bundle.noExportable": "There are no enabled personal Skills available to export.",
  "bundle.exportDialogTitle": "Export Skill Bundle",
  "bundle.fileType": "Skill Bundle",
  "bundle.formatLabel": "Skill Bundle",
  "bundle.skillsLabel": "Skills",
  "bundle.importKicker": "Bundle Import",
  "bundle.importVerified": "Verified, Not Installed",
  "bundle.staged": "Staged",
  "bundle.notInstalled": "Not installed",
  "bundle.skillsInside": "Skills in Bundle",
  "bundle.previewPrompt": "Select a file to preview verified staged content.",
  "bundle.stagedStatus": "Content is verified and staged in the app cache.",
  "bundle.stagedNotInstalled": "Content is verified and staged in the app cache. Nothing is installed.",
  "bundle.discard": "Discard Staging",
  "bundle.reviewInstall": "Review Installation",
  "bundle.installResult": "Installation Result",
  "bundle.receipt": "Receipt",
  "bundle.processed": "Processed",
  "bundle.chooseImport": "Choose Skill Bundle",
  "bundle.previewLoading": "Reading verified staged content.",
  "bundle.previewBinary": "This file is not UTF-8 text. Its complete hash is still verified.",
  "bundle.compareLoading": "Rechecking both revisions and file contents.",
  "bundle.compareTitle": "Version Comparison · {path}",
  "bundle.importedVersion": "Imported Version",
  "bundle.currentVersion": "Current Version",
  "bundle.exportBlock.credential-path": "The path looks intended for credentials; export blocked.",
  "bundle.exportBlock.private-key-material": "Private-key material was found; export blocked.",
  "bundle.exportBlock.known-token-format": "Content matches a known token format; export blocked.",
  "bundle.exportBlock.credential-assignment": "High-confidence credential assignment found; export blocked.",
  "bundle.exportBlock.resource-limit": "The Skill exceeds Bundle v1 file, size, or depth limits.",
  "bundle.exportBlock.bundle-size-limit": "The selection exceeds the Bundle v1 archive limit.",
  "bundle.exportBlock.unsafe-entry": "The Skill contains a link, special file, or unsupported path.",
  "bundle.exportBlock.source-changed": "The Skill changed during the check. Review it again.",
  "bundle.exportBlock.source-not-exportable": "Bundle v1 exports enabled personal Skills only.",
  "bundle.exportBlock.duplicate-selection": "The same Skill was selected more than once.",
  "bundle.exportBlock.skill-not-found": "The Skill is no longer in the catalog. Refresh and try again.",
  "bundle.exportBlock.default": "This Skill cannot currently be exported.",
  "bundle.status.installed": "Installed",
  "bundle.status.replaced": "Replaced",
  "bundle.status.skippedIdentical": "Skipped identical",
  "bundle.status.failed": "Failed",
  "bundle.classification.new": "New Skill",
  "bundle.classification.identical": "Identical · skipped",
  "bundle.classification.userConflict": "Personal conflict",
  "bundle.classification.managedConflict": "Managed conflict",
  "bundle.classification.incompatible": "Incompatible",
  "bundle.delta.unchanged": "Same",
  "bundle.delta.modified": "Modified",
  "bundle.delta.importedOnly": "Imported only",
  "bundle.delta.currentOnly": "Current only",
  "bundle.sameNameHeading": "Same-name versions · {count}",
  "bundle.sameRevision": "Complete revision is identical",
  "bundle.different": "Different",
  "bundle.revision": "Skill revision {revision}",
  "bundle.revisionUnavailable": "This directory has no measurable migration revision",
  "bundle.replacePersonal": "Replace the current personal Skill with the imported version",
  "bundle.installVersion": "Install this imported version",
  "bundle.selectionReview": "Review installation for {count}",
  "bundle.selectionReviewEmpty": "Review installation",
  "bundle.sourceFile": "Source file",
  "bundle.sourceFileRevision": "Source file revision",
  "bundle.bundleRevision": "Bundle revision",
  "bundle.fileCountWithBytes": "{count} · {bytes}",
  "bundle.auditPrefix": "Audit: {label}",
  "bundle.compatibilityHeading": "Codex compatibility",
  "bundle.verifiedFiles": "Verified files",
  "bundle.unknownDecision": "The relationship between this Skill and the current catalog could not be determined.",
  "bundle.decision.identical": "At least one same-name Skill has an identical complete revision and will be skipped.",
  "bundle.decision.managedConflict": "A different system or plugin Skill exists. It cannot be installed or overwritten.",
  "bundle.decision.userConflict": "A different personal version exists. Compare it and make an explicit decision.",
  "bundle.decision.userBlocked": "A personal conflict exists and the baseline check has blocking findings, so installation cannot continue.",
  "bundle.decision.newBlocked": "No same-name Skill exists, but the baseline check has blocking findings.",
  "bundle.decision.new": "No same-name Skill exists. It can proceed to installation confirmation.",
  "bundle.decision.incompatible": "This Skill does not meet the current Codex compatibility or review requirements.",
  "bundle.offer.replace": "The current enabled personal Skill will be replaced; disabled and archived versions stay unchanged.",
  "bundle.offer.createDormant": "An enabled personal Skill will be created; disabled and archived versions stay unchanged.",
  "bundle.offer.create": "Installation uses an empty destination only. It stops if the destination exists and never overwrites it.",
  "bundle.installPreviewMissing": "Reading verified staged content.",
  "bundle.installPreviewNonText": "This file is not UTF-8 text. Its complete hash is still verified.",
  "bundle.installPreviewTruncated": "Showing only the first {bytes}; the complete file hash is still verified.",
  "bundle.fileComparisonMissing": "This version does not contain this file.",
  "bundle.fileComparisonNonText": "This file is not UTF-8 text.",
  "bundle.fileComparisonTruncated": "Showing only the first {bytes}.",
  "bundle.installCurrent": "Replace the current enabled personal Skill",
  "bundle.installEnabled": "Install as an enabled personal Skill",
  "bundle.installConfirmTitle": "Install selected Skill versions",
  "bundle.installConfirmMessage": "The Bundle, all same-name versions, and the destination will be rechecked before installation.{recovery}",
  "bundle.recoveryNotice": " A recovery copy will be kept for any replaced personal Skill.",
  "bundle.installStatus": "Installation result: {installed} completed{skipped}{failed}{restart}.",
  "bundle.skippedSuffix": " · {count} identical skipped",
  "bundle.failedSuffix": " · {count} failed",
  "bundle.restartSuffix": " · Restart Codex to load the changes",
  "bundle.partialFailure": "Some Skills could not be installed. Review each receipt.",
  "bundle.allProcessed": "The selected Skill versions were processed.",
  "bundle.receiptRefreshFailed": "The receipt was kept; refreshing the catalog failed: {message}",
  "bundle.staleRefreshFailed": "A same-name version changed and the refresh failed. Import again before comparing or installing.",
  "bundle.receiptRetained": "The receipt was kept, but the catalog could not be refreshed. Import again before comparing or installing.",
  "bundle.previewImportTitle": "Version comparison · {path}",
  "bundle.previewImportVersion": "Imported version",
  "bundle.previewCurrentVersion": "Current version",
  "bundle.viewRevision": "View Skill revision",
  "bundle.executableAfterInstall": "Executable after installation",
  "bundle.viewSha": "View SHA-256",
  "bundle.selectionCount": "{count} selected",
  "bundle.skillFileCount": "{count} files",
  "bundle.importCompatible": "Meets baseline requirements",
  "bundle.importReview": "Needs review",
  "bundle.importIncompatible": "Incompatible",
  "settings.title": "Settings",
  "settings.deepAudit": "Deep Audit",
  "settings.apiMode": "API Mode",
  "settings.baseUrl": "OpenAI-compatible API Base URL",
  "settings.apiKey": "API key",
  "settings.modelPlaceholder": "Model name",
  "settings.remove": "Remove Configuration",
  "settings.test": "Test Connection",
  "settings.testing": "Testing",
  "settings.connecting": "Connecting...",
  "settings.connectionSuccess": "Connected · {mode} · {endpoint}",
  "settings.connectionFailed": "Connection failed: {message}",
  "settings.saveAction": "Save Configuration",
  "settings.keyStoredPlaceholder": "Stored; leave blank to keep using it",
  "settings.keyPlaceholder": "Enter API key",
  "settings.keyStored": "The API key is stored in this Mac's private app directory and is never shown, logged, or exported. Software running as the same macOS account may still access it.",
  "settings.keyWillStore": "The API key will be stored in a private app directory readable only by the current macOS account. Software running as the same account may still access it.",
  "settings.saved": "Deep Audit configuration and API key saved on this Mac.",
  "settings.removeTitle": "Remove Deep Audit Configuration",
  "settings.removeMessage": "This removes the saved API mode, endpoint, model name, and local API key.",
  "settings.removeConfirm": "Remove Configuration",
  "settings.removed": "Deep Audit configuration removed.",
  "consent.kicker": "Confirm Before Sending",
  "consent.title": "Choose Files That Leave This Mac",
  "consent.apiAddress": "API Address",
  "consent.run": "Send and Run Audit",
  "consent.running": "Auditing",
  "consent.requestCount": "{count} requests (threat review + false-positive review)",
  "consent.notUploaded": "{count} files will not be uploaded",
  "consent.notUploadedDefault": "Files Not Uploaded",
  "consent.completed": "Deep Audit complete.",
  "deep.skippedSummary": "{count} files will not be uploaded",
  "deep.fileMetadata": "{size} · SHA-256 {hash}{required}",
  "deep.requiredSuffix": " · Required",
  "deep.notConfigured": "No Deep Audit model is configured. Open Settings and enter an API mode, Base URL, model, and API key.",
  "confirm.title": "Confirm Action",
  "confirm.typeName": "Enter the Skill name to confirm",
  "confirm.submitting": "Submitting",
  "error.operationUnavailable": "This action will be available in a later phase.",
  "error.providerNotConfigured": "No Deep Audit model is configured. Open Settings and enter an API mode, Base URL, model, and API key.",
  "error.generic": "The action did not complete. Try again.",
  "editor.created": "Skill created. Use a new task to load the latest version.",
  "editor.createConfirmTitle": "Create New Skill",
  "editor.createRiskMessage": "Cloud Deep Audit retained high-impact findings. After reviewing the evidence, SKILL.md will still be created at {destination}.",
  "editor.createMessage": "SKILL.md will be created at {destination}.",
  "editor.confirmCreate": "Confirm Creation",
  "editor.reviewSaveTitle": "Save Draft Requiring Review",
  "editor.reviewSaveDeepMessage": "Cloud Deep Audit retained high-impact findings. Review the evidence and confirm the behavior before saving.",
  "editor.reviewSaveMessage": "The check found behavior requiring human review. Confirm that it is expected before saving.",
  "editor.confirmSave": "Confirm Save",
  "editor.discardTitle": "Discard Unsaved Changes",
  "editor.discardMessage": "Closing will discard this draft's changes.",
  "editor.discard": "Discard Changes",
  "lifecycle.disableTitle": "Disable Skill",
  "lifecycle.disableMessage": "Disable {name}? New tasks will no longer load it.",
  "lifecycle.disableConfirm": "Confirm Disable",
  "lifecycle.enableTitle": "Enable Skill",
  "lifecycle.enableMessage": "Restore {name} to personal Skills?",
  "lifecycle.enableConfirm": "Confirm Enable",
  "lifecycle.archiveTitle": "Archive Skill",
  "lifecycle.archiveMessage": "Move {name} into the recoverable archive?",
  "lifecycle.archiveConfirm": "Confirm Archive",
  "lifecycle.restoreTitle": "Restore Skill",
  "lifecycle.restoreMessage": "Restore {name} as an enabled personal Skill?",
  "lifecycle.restoreConfirm": "Confirm Restore",
  "lifecycle.deleteTitle": "Delete Skill Permanently",
  "lifecycle.deleteMessage": "Permanently delete {name} and all its files? This cannot be undone.",
  "lifecycle.deleteConfirm": "Delete Permanently",
  "lifecycle.destinationConflict": "A same-name directory already exists at {path}",
  "lifecycle.deleted": "{name} was deleted permanently.",
  "lifecycle.completed": "{action} complete. Use the latest state in a new task.",
  "lifecycle.destination": "Destination: {path}",
  "lifecycle.actionDisable": "Disable",
  "lifecycle.actionEnable": "Enable",
  "lifecycle.actionArchive": "Archive",
  "lifecycle.actionRestore": "Restore",
  "copy.serverPrompt": "Server installation instruction copied.",
  "error.code.SKILL_NOT_FOUND": "This Skill was not found. Refresh and try again.",
  "error.code.READ_ONLY_SOURCE": "Only personal Skills can be edited.",
  "error.code.INVALID_DRAFT": "The draft is required and must be at most 64 KiB.",
  "error.code.STALE_DRAFT": "This Skill changed after the draft was opened. Refresh before saving.",
  "error.code.STALE_PREVIEW": "The draft changed after preview. Review it again.",
  "error.code.NAME_CONFLICT": "A same-name Skill already exists in the catalog.",
  "error.code.INVALID_LIFECYCLE_ACTION": "This Skill state action is not recognized.",
  "error.code.LIFECYCLE_NOT_ALLOWED": "The current source does not allow this state action.",
  "error.code.STALE_DIRECTORY": "The Skill directory changed after preview. Review the action again.",
  "error.code.DELETE_CONFIRMATION_MISMATCH": "Enter the exact archived Skill name to confirm permanent deletion.",
  "error.code.BLOCKING_FINDINGS": "Resolve blocking findings first.",
  "error.code.UNSAFE_PATH": "Editing linked or escaped Skill files is not supported.",
  "error.code.INVALID_PACKAGE_PATH": "The Package path is invalid. Use a relative path inside the Skill only.",
  "error.code.PACKAGE_TOO_LARGE": "The Package exceeds the supported file count or size limits.",
  "error.code.PACKAGE_PATH_CONFLICT": "That file or folder path already exists.",
  "error.code.INVALID_COLLECTION_NAME": "Collection names must contain 1 to 60 visible characters.",
  "error.code.COLLECTION_NOT_FOUND": "That Collection no longer exists. Refresh and try again.",
  "error.code.DUPLICATE_COLLECTION_NAME": "A Collection with that name already exists.",
  "error.code.INVALID_COLLECTION_STORE": "The local Collections data is invalid or exceeds limits.",
  "error.code.COLLECTION_IO_ERROR": "Local Collections could not be read or written.",
  "error.code.LOCAL_IO_ERROR": "The local Skill workspace could not be accessed.",
  "error.code.INVALID_GITHUB_CANDIDATE_URL": "Enter a public github.com repository or Skill directory URL.",
  "error.code.INVALID_LOCAL_CANDIDATE": "The selected candidate must be a real folder, not a link.",
  "error.code.MISSING_SKILL_DOCUMENT": "SKILL.md must remain at the Skill Package root.",
  "error.code.NO_REPOSITORY_SKILLS": "This repository has no root Skill or Skill at a supported level under skills/.",
  "error.code.REPOSITORY_SKILL_LIMIT": "This repository has more than 256 discoverable Skills, so no partial list was created.",
  "error.code.UNSAFE_CANDIDATE_ENTRY": "The candidate contains an unsafe or unsupported entry.",
  "error.code.CANDIDATE_FILE_LIMIT": "The candidate has too many files. The limit is 256.",
  "error.code.CANDIDATE_FILE_SIZE_LIMIT": "A candidate file exceeds 2 MiB.",
  "error.code.CANDIDATE_TOTAL_SIZE_LIMIT": "The candidate exceeds the 25 MiB staging limit.",
  "error.code.CANDIDATE_DEPTH_LIMIT": "The candidate directory is too deep.",
  "error.code.GITHUB_TREE_LIMIT": "The GitHub tree was truncated or exceeded the response limit.",
  "error.code.INCONSISTENT_GITHUB_SOURCE": "The GitHub source changed during acquisition. Try again.",
  "error.code.GITHUB_RATE_LIMIT": "The GitHub rate limit was reached. Try again later.",
  "error.code.GITHUB_ACQUISITION_ERROR": "The GitHub candidate could not be acquired. Check the network and try again.",
  "error.code.UNKNOWN_CANDIDATE_SESSION": "The candidate staging session ended. Import it again.",
  "error.code.STALE_CANDIDATE": "The staged candidate changed. Start the review again.",
  "error.code.UNKNOWN_CANDIDATE_FILE": "This file is not part of the staged candidate.",
  "error.code.INVALID_CANDIDATE_FILE_SYNC": "This file cannot use the selected sync action. Check for updates again.",
  "error.code.INVALID_PACKAGE_OPERATION": "This file operation is not recognized. Check for updates again.",
  "error.code.BINARY_PACKAGE_FILE": "Binary files cannot be edited directly as text.",
  "error.code.CANDIDATE_IO_ERROR": "The candidate could not be staged in the app cache.",
  "error.code.GITHUB_UPDATE_PROVENANCE_UNAVAILABLE": "There is not enough GitHub provenance evidence to check for updates.",
  "error.code.GITHUB_UPDATE_READ_ONLY": "Only user-controlled Skills can check for GitHub updates.",
  "error.code.CANDIDATE_INSTALL_BLOCKED": "The candidate cannot be installed while blocking or compatibility issues remain.",
  "error.code.STALE_INSTALL_PREVIEW": "The installation preview changed. Review the destination again.",
  "error.code.DEEP_AUDIT_NOT_CONFIGURED": "No Deep Audit model is configured.",
  "error.code.INVALID_PROVIDER_ENDPOINT": "Enter a valid HTTPS API Base URL. HTTP is allowed only for loopback addresses.",
  "error.code.INVALID_PROVIDER_MODEL": "Enter a model name.",
  "error.code.STALE_DEEP_AUDIT_PREVIEW": "The Deep Audit preview is stale. Review the provider and files again.",
  "error.code.INVALID_DEEP_AUDIT_SELECTION": "The selected Deep Audit files are invalid. Review the file list again.",
  "error.code.DEEP_AUDIT_PROVIDER_ERROR": "The cloud model request failed. Check the provider and network.",
  "error.code.INVALID_PROVIDER_RESPONSE": "The cloud model did not return verifiable structured evidence.",
  "error.code.CREDENTIAL_STORE_ERROR": "The local Deep Audit credential could not be read or stored securely.",
  "error.code.PREFERENCES_ERROR": "Deep Audit settings could not be read or saved.",
  "error.code.BUNDLE_EXPORT_SELECTION_INVALID": "Select at least one personal Skill.",
  "error.code.BUNDLE_EXPORT_PLAN_STALE": "The export preview is stale. Review the selected Skills again.",
  "error.code.BUNDLE_EXPORT_SOURCE_CHANGED": "A Skill changed before export. Review the export again.",
  "error.code.BUNDLE_EXPORT_DESTINATION_INVALID": "Choose a new .skillbundle file in an existing folder.",
  "error.code.BUNDLE_EXPORT_DESTINATION_EXISTS": "A same-name file already exists there. Choose another name.",
  "error.code.BUNDLE_EXPORT_IO_ERROR": "The Bundle could not be written to the selected location.",
  "error.code.BUNDLE_IMPORT_SOURCE_INVALID": "Choose a regular .skillbundle file.",
  "error.code.BUNDLE_IMPORT_SOURCE_CHANGED": "The Bundle changed while being read. Choose it again.",
  "error.code.BUNDLE_IMPORT_SESSION_UNKNOWN": "The Bundle staging session ended. Import it again.",
  "error.code.BUNDLE_IMPORT_SESSION_CHANGED": "The staged Bundle content changed. Import it again.",
  "error.code.BUNDLE_LIMIT_EXCEEDED": "The Bundle exceeds the accepted size or file-count limits.",
  "error.code.BUNDLE_IMPORT_IO_ERROR": "The Bundle could not be staged in the app cache.",
  "error.code.BUNDLE_INSTALL_REVIEW_STALE": "The installation review is stale. Review the latest same-name versions.",
  "error.code.BUNDLE_INSTALL_MATCH_UNKNOWN": "A same-name version changed. Review the comparison again.",
  "error.code.BUNDLE_INSTALL_FILE_UNKNOWN": "This file is not part of the current comparison.",
  "error.code.BUNDLE_INSTALL_SELECTION_INVALID": "Select at least one currently installable version.",
  "error.code.BUNDLE_INSTALL_BLOCKED": "The current classification, compatibility, or findings block installation.",
  "error.code.BUNDLE_INSTALL_IO_ERROR": "Installation encountered a local file error. Review each receipt."
};

export const catalogs = Object.freeze({ "zh-CN": Object.freeze(zhCN), en: Object.freeze(en) });

export function normalizeLocale(value) {
  return SUPPORTED_LOCALES.includes(value) ? value : DEFAULT_LOCALE;
}

export function catalogParity() {
  const expected = Object.keys(catalogs[DEFAULT_LOCALE]).sort();
  return Object.fromEntries(SUPPORTED_LOCALES.map((locale) => {
    const actual = Object.keys(catalogs[locale]);
    return [locale, {
      missing: expected.filter((key) => !actual.includes(key)),
      extra: actual.filter((key) => !expected.includes(key)).sort()
    }];
  }));
}

function interpolate(message, values) {
  return message.replace(/\{([A-Za-z0-9_]+)\}/g, (match, key) => (
    Object.hasOwn(values, key) ? String(values[key]) : match
  ));
}

export function createLocalization({ storage, document: rootDocument } = {}) {
  let locale = normalizeLocale(storage?.getItem?.(LOCALE_STORAGE_KEY));
  const listeners = new Set();

  function t(key, values = {}) {
    const message = catalogs[locale][key] ?? catalogs[DEFAULT_LOCALE][key];
    if (message === undefined) return key;
    return interpolate(message, values);
  }

  function apply(root = rootDocument) {
    if (!root?.querySelectorAll) return;
    rootDocument.documentElement.lang = locale;
    for (const node of root.querySelectorAll("[data-i18n]")) {
      node.textContent = t(node.dataset.i18n);
    }
    for (const attribute of ["aria-label", "title", "placeholder"]) {
      const dataName = `i18n${attribute.split("-").map((part) => part[0].toUpperCase() + part.slice(1)).join("")}`;
      for (const node of root.querySelectorAll(`[data-${dataName.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`)}]`)) {
        node.setAttribute(attribute, t(node.dataset[dataName]));
      }
    }
  }

  function setLocale(value) {
    const next = normalizeLocale(value);
    if (next === locale) return false;
    locale = next;
    storage?.setItem?.(LOCALE_STORAGE_KEY, locale);
    apply(rootDocument);
    for (const listener of listeners) listener(locale);
    return true;
  }

  function subscribe(listener) {
    listeners.add(listener);
    return () => listeners.delete(listener);
  }

  return {
    get locale() {
      return locale;
    },
    t,
    apply,
    setLocale,
    subscribe
  };
}
